### ISSUE TITLE
printCSS

### ISSUE THREAD

**Issue by RogerHuangZB** [laixiangran/e-ngx-print#3] opened 2017-08-17 08:57 UTC
printCSS（?Array<string>） - 打印内容css文件路径。将在打印页面生成link标签，支持绝对/相对路径（相对于当前路由地址）

如何理解 相对于当前路由地址？

我必须引用项目外部的CSS文件吗？

以下路径不生效：
```
this.printCSS = ['xxx.component.css'];
this.printCSS = ['./xxx.component.css'];
```

**Comment by laixiangran** [comment] 2017-08-18 14:25
最好就是用绝对路径吧，好理解一点，比如http://localhost/assets/styles/xxx.css。

**Comment by M1kemay** [comment] 2017-09-28 00:06
Hi, thanks for creating this, works great with my app.

when i link to my .CSS using 
`this.printCSS = [ 'http://localhost:xxxx/src/app/styles/xxxx.component.css' ];`
I get this error in the browser console:

`Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:xxxx/src/app/styles/xxxx.component.css".`

and the styles do not apply to the printed section. Is there any way to fix this?

**Comment by laixiangran** [comment] 2017-09-28 08:49
@M1kemay You mean the problem has been solved?

**Comment by M1kemay** [comment] 2017-09-28 12:14
@laixiangran yes and no. Classes or ID fields do not appear to fully work, but i was able to work around it by using direct elements only (see edit 1). Apologies for the confusion.

**Comment by laixiangran** [comment] 2017-09-29 03:28
@M1kemay When generating the print page, I first create the style tag and then create the link tag.About edit 1, whether the style in the CSS file is covered in the style tag.

**Comment by M1kemay** [comment] 2017-10-02 21:16
@laixiangran I have gotten it to appear as intended. Not sure why class and ID tags don't work (for me), but that may be due to something i missed in my own programming. I must apologize as well. I should have tried writing my .CSS from scratch instead of copy-pasting my currently existing file.

**Comment by M1kemay** [comment] 2017-10-20 00:52
Not entirely sure if this is related. I can print OK from my computer. but when I access my application from another computer on the network and try to print, it comes up blank. 

when i right click on the page and click print it works, not sure why the print button does not. it happens with chrome and system dialog printing.

i was able to print with Internet explorer too but it lost all formatting. likely because it's internet explorer.

**Closed** 2018-02-14 02:05 UTC
